// Autogenerated from Pigeon (v24.2.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct BiometricAuthResult {
  var success: Bool? = nil
  var errorMessage: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BiometricAuthResult? {
    let success: Bool? = nilOrValue(pigeonVar_list[0])
    let errorMessage: String? = nilOrValue(pigeonVar_list[1])

    return BiometricAuthResult(
      success: success,
      errorMessage: errorMessage
    )
  }
  func toList() -> [Any?] {
    return [
      success,
      errorMessage,
    ]
  }
}

private class BiometricAuthApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return BiometricAuthResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class BiometricAuthApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? BiometricAuthResult {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class BiometricAuthApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return BiometricAuthApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return BiometricAuthApiPigeonCodecWriter(data: data)
  }
}

class BiometricAuthApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = BiometricAuthApiPigeonCodec(readerWriter: BiometricAuthApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BiometricAuthApi {
  func isBiometricAvailable(completion: @escaping (Result<Bool, Error>) -> Void)
  func authenticateUser(reason: String, completion: @escaping (Result<BiometricAuthResult, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BiometricAuthApiSetup {
  static var codec: FlutterStandardMessageCodec { BiometricAuthApiPigeonCodec.shared }
  /// Sets up an instance of `BiometricAuthApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BiometricAuthApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let isBiometricAvailableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.seek_project.BiometricAuthApi.isBiometricAvailable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isBiometricAvailableChannel.setMessageHandler { _, reply in
        api.isBiometricAvailable { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      isBiometricAvailableChannel.setMessageHandler(nil)
    }
    let authenticateUserChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.seek_project.BiometricAuthApi.authenticateUser\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      authenticateUserChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let reasonArg = args[0] as! String
        api.authenticateUser(reason: reasonArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      authenticateUserChannel.setMessageHandler(nil)
    }
  }
}
